on:
  push:
    tags:
      - '*'
    branches:
      - main

name: Build Project
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU dependency
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build project
        run: ./build.sh

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: ipks
          path: tmp/packages/*.ipk
          # These files are already compressed
          compression-level: 0


  create-release:
    name: Create Release
    runs-on: ubuntu-24.04
    if: github.ref_type == 'tag'
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ipks

      # TODO: Use a glob if we need to upload more files
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.ipk"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}