on:
  push:
    branches:
      - main

name: Build Project
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: ./build.sh

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          path: '*.tar.gz'
          # These files are already compressed
          compression-level: 0
