on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: ./build.sh

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: python-3.13-alpine3.21-armv7-musl
          path: 'python-3.13-alpine3.21-armv7-musl.tar.gz'
          # These files are already compressed
          compression-level: 0

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          pattern: '*'

      # TODO: Use a glob if we need to upload more files
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            python-3.13-alpine3.21-armv7-musl.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
